#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "Execute to root!"
    echo "nmap_scan 192.168.1.1 192.168.1.10 ...."
    exit 1
fi

echo "NMAP scanning execute to root"

exec > >(tee -a "nmap_results_$(date +%Y-%m-%d).txt") 2>&1

for ip in "$@"; do
        nmap -p- -Pn $ip -v --min-rate 1000 --max-rtt-timeout 1000ms --max-retries 5 --open -oN "${ip}_nmap_all_ports.txt"


        ports=$(grep '^[0-9]' "${ip}_nmap_all_ports.txt" | cut -d'/' -f1 | tr '\n' ',' | sed 's/,$//')

        echo "-----------------------------------------"
        echo "Ports TCP: $ports "
        echo "To $ip results"
        echo "-----------------------------------------"
        nmap -Pn $ip -sV -sC -A -v -p$ports  -oN "${ip}_nmap_complete.txt"

done
